const str = `O homem é o próprio lobo do homem`

console.log(str.length)
console.log(str.indexOf('homem'))
console.log(str.charAt(10))
console.log(str.charCodeAt(2))
console.log(str.split('homem'))
console.log(str.concat(' sim', ' porque', ' eu', ' quero' ))
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.replace('lobo', 'monstro'))
console.log(str.replace('homem', 'pessoa'))
console.log(str.replaceAll('homem', 'pessoa'))
console.log(str.replace(/homem/g, 'pessoa'))
console.log(str.replaceAll('homem', 'pessoa'))
console.log(str.replace(/homem/gi, 'pessoa'))
console.log(str.startsWith('O homem'))
console.log(str.endsWith('Homem'))
console.log(str.slice(5))
console.log(str.slice(12, 24))
console.log(str.slice(-21))